version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: project_management_db
    environment:
      POSTGRES_DB: project_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: project_management_backend
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://postgres:password123@postgres:5432/project_management
      JWT_SECRET: your_jwt_secret_here
      JWT_EXPIRES_IN: 24h
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - project_network
    command: npm run dev

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: project_management_frontend
    environment:
      VITE_API_URL: http://localhost:3001/api
      VITE_APP_NAME: Project Management System
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - project_network
    command: npm run dev

  # Redis for caching and sessions (optional)
  redis:
    image: redis:7-alpine
    container_name: project_management_redis
    ports:
      - "6379:6379"
    networks:
      - project_network

volumes:
  postgres_data:

networks:
  project_network:
    driver: bridge 